use_frameworks!

target 'FirebaseStorageCacheable_Example' do
  pod 'Firebase/Storage', '~> 3.1'
  pod 'FirebaseStorageCacheable', :path => '../'

  target 'FirebaseStorageCacheable_Tests' do
    inherit! :search_paths

    
  end
end
